connect_headers: &connect_headers
  accept-version: "1.2"
  host: localhost,
  heart-beat: "59000,59000"

default: &default
  hosts:
    -
      host: activemq
      port: 61613
      ssl: false
      login: <%= ENV.fetch("ACTIVEMQ_READ_USER", 'consumer') %>
    - passcode: <%= ENV.fetch("ACTIVEMQ_READ_PASS", 'consumer') %>
  max_reconnect_attempts: 5
  connect_timeout: 2
  connect_headers:
    <<: *connect_headers

production:
  host: <%= ENV.fetch("ACTIVEMQ_HOST", '') %>
  port: <%= ENV.fetch("ACTIVEMQ_PORT", '') %>
  ssl: true
  read_user: <%= ENV.fetch("ACTIVEMQ_READ_USER", 'consumer') %>
  read_pass: <%= ENV.fetch("ACTIVEMQ_READ_PASS", 'consumer') %>
  max_reconnect_attempts: 5
  connect_timeout: 2
  connect_headers:
    <<: *connect_headers

development:
  <<: *default
  connect_headers:
    <<: *connect_headers
  
test:
  <<: *default
  connect_headers:
    <<: *connect_headers
